#ifndef __ChessScoreBoardMainFrame__
#define __ChessScoreBoardMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "generated.h"
#include "../Logic/Score.hpp"
#include <vector>

//// end generated include



/** Implementing MainFrame */
class ChessScoreBoardMainFrame: public MainFrame
{
private:

    std::vector<Score> Scores;

    void UpdateText();

    void AddScore(Score result);

    void RemoveScore();

protected:
    // Handlers for MainFrame events.
    void OnButtonLosePlus(wxCommandEvent &event) override;
    void OnButtonDrawPlus(wxCommandEvent &event) override;
    void OnButtonWinPlus(wxCommandEvent &event) override;
    void OnButtonReset(wxCommandEvent &event) override;
    void OnButtonUndo(wxCommandEvent &event) override;
public:
    /** Constructor */
    explicit ChessScoreBoardMainFrame(wxWindow *parent);
    //// end generated class members



};

#endif // __ChessScoreBoardMainFrame__
